import Layout from "./Layout";
import Sidebar from "./Sidebar";
import Footer from "./Footer";
import Modal from "./Modal";
import Particle from "./Particle";
import Hero from "./Hero";
import About from "./About";
import Projects from "./Projects";
import Contact from "./Contact";
import Loader from "./Loader";
import TypedHeading from "./global/TypedHeading";
export { Layout, Modal, Sidebar, Footer, Particle, Hero, About, Projects, Contact, Loader, TypedHeading };
